[package]
name = "wasm-verifier"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
risc0-zkvm = { version ="=2.2.0", default-features = false, features = ["std"] }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
wasm-bindgen = "0.2"
